### ISSUE TITLE
not all tokens get successfully imported after using `--andotp-backup`

### ISSUE THREAD

**Issue by benoit-pierre** [puddly/android-otp-extractor#20]
Only 3 out of 7 got imported successfully. Using `--show-qr` and manually adding the missing ones work (like for Google), except for one: Steam (`Invalid QR code`).

**Comment by benoit-pierre** [comment]
Note that the Steam entry in the backup is the fourth one, and I've just read that Steam support is not enabled by default, so the issue might just be with andOTP and bad error handling/reporting.

**Comment by puddly** [comment]
Thanks for all the help. AndOTP can't actually import Steam codes even when experimental support for them is enabled. Instead, it stops the backup when an unknown code type is encountered.

**Comment by benoit-pierre** [comment]
It works after setting some missing fields and changing the type from `steam` to `STEAM`, see #21.
