### ISSUE TITLE
Google Authenticator import misses the last three keys

### ISSUE THREAD

**Issue by sebastianst** [puddly/android-otp-extractor#26]
I have 20 keys in total in my Google Authenticator and only the first 17 get extracted. I deleted one key in the middle and still, the last three keys are omitted. The verbose output doesn't show anything suspicious.

**Comment by puddly** [comment]
Can you check what the `read_google_authenticator_accounts` is doing in the inner `for` loop that iterates over the `accounts` table? It should have 20 rows.

**Comment by puddly** [comment]
The other alternative is if somehow your accounts are colliding in the `accounts` set, which would mean the `OTPAccount.as_uri()` function has a bug. If that above function correctly reads all of the accounts from the database, can you verify if `Found 20 accounts (17 new)` is printed by the script and that those last three accounts aren't being extracted from another app?

**Comment by sebastianst** [comment]
It says `Found 17 accounts (17 new)`.
I checked the sqlite3 database that is pulled from the phone and its `accounts` table indeed only contains 17 entries... Strange.

**Comment by puddly** [comment]
Where are the last three coming from? That is very strange.

**Comment by jackgreyhat** [comment]
Same issue here. Anything I can do to help troubleshooting?

**Comment by jackgreyhat** [comment]
> I forgot to answer, the last three were 2 Microsoft and 1 Namecheap. It is worth mentioning that the missing three were also the last three in the displayed order of the Google Authenticator.

I was able to migrate my Microsoft keys without issue. I assume it has to do with the key list position, not the 'vendor' or 'issuer'. Just my feeling :)

**Comment by puddly** [comment]
@jackgreyhat, @sebastianst: Could you dump the `$ANDROID_DATA/data/com.google.android.apps.authenticator2/databases/databases` file and see where these accounts are stored in the SQLite database? It could be some internal format change that's splitting the accounts into multiple tables. Something like this should work:

```sh
adb shell 'su -c "cat $ANDROID_DATA/data/com.google.android.apps.authenticator2/databases/databases | base64"' | base64 -D > authenticator.db
sqlite3 authenticator.db .schema > schema.sql
sqlite3 authenticator.db .dump > rows.sql  # Sanitize this by hand
```

Replace any secrets and sensitive account names in `rows.sql` and post the contents of both files here, if you could.

**Comment by jackgreyhat** [comment]
The database contains only 14 entries. There are no 15 entries in the database, even though I have 15 keys in my authenticator!
The 'extra' key that I received by using your python migration script, is listed in the database but not in the Google Authenticator. It makes sense that your script retrieved this extra key, it makes no sense that the Google Authenticator doesn't display this key. I believe this is a key that I deleted *years* ago.
So now I have two Google Authenticator keys, which are not stored in this database, and one key which is stored in the database but not displayed in the Google Authenticator...

Do you still want to see the database structure? I'm trying to figure out where my other two extra keys are stored...

**Comment by jackgreyhat** [comment]
I figure it out...
It must have something to do with caches or temp databases.

I used TitaniumBackup to backup the Google Authenticator just now. Somehow it 'forces' the authenticator to review/check its database. *After* the TitaniumBackup, I now have 15 keys in my database. There is also no old key in the database anymore.

So something that TitaniumBackup is doing, fixes the issue of the database being outdated. This, in turn, should fix your script. However, it does not. It still only detects 14 accounts. Does this script use it's own temp somewhere? Perhaps it is still using data that was generated yesterday?

**Comment by puddly** [comment]
My script essentially runs the first and last of those three commands I posted earlier, there's no caching. The only data stored by Google Authenticator on my phone is:

```
./cache
./code_cache
./shared_prefs
./shared_prefs/persistent_backup_agent_helper.xml
./shared_prefs/com.google.android.apps.authenticator2_preferences.xml
./databases
./databases/databases
./databases/databases-journal
./files
```

The preferences files each contain one key, leaving `database` as the only other place to store data.

How are you counting that you have 15 keys in your database?

**Comment by puddly** [comment]
@sebastianst @jackgreyhat Have either of you used Titanium Backup or a similar tool to restore Google Authenticator from a previous backup? I'm unable to get anything to act strangely after using two different backup apps.

**Comment by sebastianst** [comment]
I have indeed transported my Google Authenticator between roms and phones several times using TB.

**Comment by puddly** [comment]
@sebastianst if you haven't touched your Authenticator database yet with another tool, could you run those three commands I have above?

That's sounding like the issue so I'll have to give that a try on another phone. Do you know approximately what major versions of Android you used? Were they all mostly stock ROMs?

**Comment by sebastianst** [comment]
OK here's the schema
```sql
CREATE TABLE android_metadata (locale TEXT);
CREATE TABLE accounts (_id INTEGER PRIMARY KEY, email TEXT NOT NULL, secret TEXT NOT NULL,  counter INTEGER DEFAULT 0, type INTEGER, provider INTEGER DEFAULT 0, issuer TEXT DEFAULT NULL, original_name TEXT DEFAULT NULL);
```
I don't feel comfortable posting any content from the dump on a public github issue though ;)
What I can tell you is that I see all but the two missing Microsoft dumps (I deleted the other one already) and they are all of the form
```sql
INSERT INTO accounts VALUES(1,'my@email.address','secretkey123',0,0,0,'Company or NULL','email/company or NULL');
```
the secret keys are all alpha-numerical, of varying length, sometimes upper, sometimes lower-case.

btw, I didn't need to base64 the data for pipe transfer, this just worked:
```sh
adb shell 'su -c "cat $ANDROID_DATA/data/com.google.android.apps.authenticator2/databases/databases"' > authenticator.db
```

**Comment by sebastianst** [comment]
I've been using Titanium Backup and Authenticator since my first phone (HTC Desire), on rooted stock and heavily customized roms, and everything in between, different phones, and probably all android versions since 2011 (so probably since Android 2.2) ;)

**Comment by puddly** [comment]
@sebastianst I see. As a last resort, can you rename one of those unexportable accounts to something unique, exit out of Authenticator, and do a `grep -ra 'unique_name' $ANDROID_DATA/data/` as root to see where in the world it's being stored?

**Comment by sebastianst** [comment]
I just discovered two more files, next to the database, in the `databases` folder:
```sh
walleye:/data/data/com.google.android.apps.authenticator2/databases # ls -l
total 76
-rw-rw---- 1 u0_a148 u0_a148  6144 2018-09-25 22:21 databases
-rwxrw---- 1 u0_a148 u0_a148 32768 2019-02-10 19:04 databases-shm
-rw-rw---- 1 u0_a148 u0_a148 17848 2019-01-31 21:13 databases-wal
```
The `-shm` and `-wal` files come form [sqlite's _Write-Ahead Loggging_ mode](https://www.sqlite.org/wal.html). Now guess what I find in the binary data of the `-wal` file? My missing Microsoft tokens.
So I guess now we have to find a way to either extract the tokens right from the WAL or somehow make sqlite establish the current state in the actual `database` file.

**Comment by sebastianst** [comment]
OK, if all three files are next to each other, `sqlite3` automatically incorporates the data from the write-ahead log as well. So depending on the sqlite implementation used by python, simply pulling the `-wal` and `-shm` files as well should hopefully solve the issue.
