### ISSUE TITLE
Fix for #33 breaks Authy's 7 digit tokens

### ISSUE THREAD

**Issue by EccTM** [puddly/android-otp-extractor#34]
I think that the latest commit, [6270618](https://github.com/puddly/android-otp-extractor/commit/627061830900a2e9364e33b718f6f1265de6255c), caused an issue parsing Authy's 7 digit tokens, specifically Twitch and Humble Bundle in my case. I rolled back to the [previous commit](https://github.com/puddly/android-otp-extractor/commit/4cec5f86066778c1de07ec9c7c7fe820ec7db3df) and it exported all 15 accounts without issue.

Here's the output it gave on failure:
```
C:\Users\lorde\Desktop\platform-tools>python -m android_otp_extractor
2020-05-25 09:23:36 Morpheus android_otp_extractor.adb[2084] INFO Testing if your phone uses binary: 'toybox'
2020-05-25 09:23:36 Morpheus android_otp_extractor.adb[2084] INFO Listing contents of / as root
2020-05-25 09:23:36 Morpheus android_otp_extractor.adb[2084] INFO Reading and hashing contents of build.prop as root
2020-05-25 09:23:36 Morpheus android_otp_extractor.adb[2084] INFO Using command line utility binary: 'toybox'
2020-05-25 09:23:36 Morpheus android_otp_extractor.apps[2084] INFO Reading Authy accounts
2020-05-25 09:23:37 Morpheus android_otp_extractor.apps[2084] WARNING Transformed Authy secret XXX into xxx
2020-05-25 09:23:37 Morpheus android_otp_extractor.apps[2084] WARNING Transformed Authy secret YYY into yyy
Traceback (most recent call last):
  File "C:\Users\lorde\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\lorde\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lorde\AppData\Local\Programs\Python\Python37\lib\site-packages\android_otp_extractor\__main__.py", line 3, in <module>
    main()
  File "C:\Users\lorde\AppData\Local\Programs\Python\Python37\lib\site-packages\android_otp_extractor\cli.py", line 62, in main
    accounts = apps.read_accounts(adb, enabled_apps)
  File "C:\Users\lorde\AppData\Local\Programs\Python\Python37\lib\site-packages\android_otp_extractor\apps.py", line 336, in read_accounts
    new = list(app.extractor(adb))
  File "C:\Users\lorde\AppData\Local\Programs\Python\Python37\lib\site-packages\android_otp_extractor\apps.py", line 68, in read_authy_accounts
    yield TOTPAccount(account['name'], secret=base64.b32decode(pad_to_8(fixed_secret.upper())), digits=account['digits'], period=period)
  File "C:\Users\lorde\AppData\Local\Programs\Python\Python37\lib\base64.py", line 235, in b32decode
    raise binascii.Error('Incorrect padding')
binascii.Error: Incorrect padding
```

**Comment by puddly** [comment]
Can you compare the values displayed by `Transformed Authy secret` in the current commit to what's present in the `otpauth://totp/...` URIs printed by the previous one?

**Comment by EccTM** [comment]
I just re-ran both builds with the command `python -m android_otp_extractor --include authy` as I've since set up andOTP on my device, and the `Transformed Authy secret` values of the current commit don't appear to match to anything in the `otpauth://` URIs generated by the previous commit.

The previous commit `&secret=` values don't include any of the values being stripped `'1890'` from the `transformed Authy secret` at `apps.py:62` in the latest commit either.

**Comment by puddly** [comment]
I've pushed what I think to be a fix in 85473f1c37a50505afbb1b9f241bfed6d556ab67. For some reason, I cannot generate codes that match Authy's on Android, even when using much older commits.

Can you verify that the codes are still valid?

**Comment by EccTM** [comment]
I just checked that commit, and it did generate `otpauth://` lines for all 15 accounts, with secrets matching the output I got from before the #33 fix was applied. I haven't checked if the 7-digit codes it's generating for Twitch or HumbleBundle worked just yet, but I'll give them a shot and let you know. As for them not matching, could it be because the codes are valid for 10 seconds and something like andOTP treats them as such, but Authy displays each code for 20 seconds, basically skipping every second code and betting on time-sync lenience treating the stale code as valid? They just might not be lining up totally in sync.

**Comment by puddly** [comment]
Yeah, but they should still match up about 50% of the time. I tested +/- a few thousand periods and every possible interpretation of that secret. Nothing synced up.

Oddly enough, they seem to work (at least with SendGrid) so maybe I'm just missing something simple. Let me know if they don't for you. If they do, feel free to close this issue.

**Comment by EccTM** [comment]
I tested the codes generated (after feeding the `otpauth://` lines into WinAuth) for HumbleBundle and Twitch and they were accepted, but none of them matched what Authy on android was outputting for me either.

Weirdly, I tried a different script ([by you!](https://gist.github.com/gboudreau/94bb0c11a6209c82418d01a59d958c93#gistcomment-2224133)) that I stumbled across to generate the secrets from the Authy chrome app instead, and those do show matching codes occasionally for 2 or 3 seconds. That script also seems to just treat all the secrets as base32? I don't really know enough about what I'm looking at programatically to pinpoint what is happening differently between the two tbh.

**Comment by puddly** [comment]
Authy has made seemingly pointless but breaking changes to the RFC4226 HOTP algorithm, making its codes incompatible with every normal OTP app. Authy Desktop and the Chrome extension both generate codes according to RFC4226 so I'm not sure why Authy Android is now doing it this way.

When you verify an Authy code, their servers appear to check with both the RFC4226 and the "Authy" variant of RFC4226, accepting the code if either one matches. Why?

Below is a script that generates codes that are identical to those from the Android app:

```Python
import time
import hmac
import base64
import hashlib


def lenient_b32_decode(s):
    if len(s) % 8 != 0:
        s += '=' * (8 - (len(s) % 8))

    return base64.b32decode(s)


def _hotp_helper(key: bytes, msg: bytes, digits: int) -> str:
    digest = hmac.digest(
        key=key,
        msg=msg,
        digest=hashlib.sha1
    )
    i = digest[-1] & 0xF

    n = int(digest.hex()[i : i + digits], 16) % (10 ** digits)

    return str(n).zfill(digits)


def authy_hotp(secret: bytes, counter: int, digits: int) -> str:
    return _hotp_helper(
        key=secret.hex().encode('ascii'),  # The secret's hex bytes are used as the key, it is never actually decoded
        msg=str(counter).encode('ascii'),  # The counter is also treated as a base-10 string
        digits=digits
    )


def rfc4226_hotp(secret: bytes, counter: int, digits: int) -> str:
    return _hotp_helper(
        key=secret,
        msg=counter.to_bytes(8, 'big'),
        digits=digits
    )


if __name__ == '__main__':
    AUTHY_SECRET_KEY = b'fill out and uncomment one of the two following lines'

    # Taken directly from the Authy XML file
    #AUTHY_SECRET_KEY = bytes.fromhex('b4442b47f62bc29db6f75aca78f32bb1')

    # The same value as above, just decoded from hex and encoded as Base32
    #AUTHY_SECRET_KEY = lenient_b32_decode('WRCCWR7WFPBJ3NXXLLFHR4ZLWE')

    counter = int(time.time() // 10)

    authy_code = authy_hotp(
        secret=AUTHY_SECRET_KEY,
        counter=counter,
        digits=7
    )

    rfc4226_code = rfc4226_hotp(
        secret=AUTHY_SECRET_KEY,
        counter=counter,
        digits=7
    )

    print('Authy:  ', authy_code)
    print('RFC4226:', rfc4226_code)
```

OTP generation is a little out of scope for this project but hopefully this code will help one of the existing OTP apps if Authy decides to one day switch everything over to their proprietary OTP generation algorithm.

**Comment by p1r473** [comment]
Hi @puddly 
Also trying to get the built in 7 digit Humble Bundle/Twitch/Dataplicity/Drop stuff to work.

If the above code successfully generates the 7 digit code, **can you integrate it into the app so the shown code is valid?**

I know that the generation part of this project isn't the main focus, but I think we should still fix it.

**Comment by p1r473** [comment]
Can you provide any additional help in getting that script to work?
I've grabbed for example the Humble Bundle hex codes out of both com.authy.storage.tokens.authenticator.xml and also  com.authy.storage.tokens.authy.xml 
In those 2 files, multiple hex codes are provided for each Authenticator, so how can I determine which is the correct one?

**Comment by puddly** [comment]
Is there a "standard" URI protocol for these codes (maybe `authy://`)? I don't think I'm the only one that has reverse engineered the algorithm but there's no way to scan these codes into an app at the moment and distinguish them from standard TOTP codes.

Authy is validating both types of codes (for now...) so there's little point in changing the way they're locally displayed if the app that they're scanned into won't follow the same format.

**Comment by p1r473** [comment]
@puddly when I scanned the QR code produced by android-otp-extractor back into Authy, the codes it was giving was not accepted by Twitch
Any idea why? If the code you are generating was valid, Twitch should have accepted it
Thanks

**Comment by p1r473** [comment]
@puddly thank you. I was able to successfully scan the QR code generated by android-otp-extractor back into Authy and validate the code was accepted, as confirmed this matched the code generated by android-otp-extractor itself, so I agree, for now there is no reason to make the change as long as both codes are accepted.

I dont believe there is any standard for these new wonky codes.

**Comment by krisu5** [comment]
> Also trying to get the built in 7 digit Humble Bundle/Twitch/Dataplicity/Drop stuff to work.

FYI (slight offtopic sorry), Humble Bundle and Twitch doesn't force to use Authy anymore, if you don't want to. 

If you deactivate and reactivate 2FA on those services, then you can set 2FA with any TOTP app.

Only issue is that some reason Authy doesn't let you delete any of the their 2FA entries from your Authy account.

**Comment by p1r473** [comment]
> > Also trying to get the built in 7 digit Humble Bundle/Twitch/Dataplicity/Drop stuff to work.
> 
> FYI (slight offtopic sorry), Humble Bundle and Twitch doesn't force to use Authy anymore, if you don't want to.
> 
> If you deactivate and reactivate 2FA on those services, then you can set 2FA with any TOTP app.
> 
> Only issue is that some reason Authy doesn't let you delete any of the their 2FA entries from your Authy account.

Thanks! Just switched over. Now if only Dataplicity and Drop would do the same.
