### ISSUE TITLE
Tutorial on install

### ISSUE THREAD

**Issue by QuartzWarrior** [puddly/android-otp-extractor#50]
I have tried to use this multiple times on termux and it has failed, looping over the dependencies. Can you create a tutorial for this? And yes, my phone is rooted.

**Comment by puddly** [comment]
Make sure you have a valid Python version installed (3.6 or newer):

```console
$ python -V
Python 3.9.7

$ pip -V
pip 20.3.4 from /usr/lib/python3.9/site-packages/pip (python 3.9)
```

If `pip` doesn't point to the Python 3 installation, try `pip3`. If that doesn't work, try `python -m pip`:

```console
$ python -m pip install git+https://github.com/puddly/android-otp-extractor
```

**Comment by QuartzWarrior** [comment]
Hold up, am I supposed to run this on my computer or on the phone?

**Comment by puddly** [comment]
Oh, on your computer. It connects to your phone over adb.

**Comment by QuartzWarrior** [comment]
Oh lmao, you should make that clear in the Readme, that's why it was not working.
